files:
  - source: en.json
    ignore:
      - /zh*
      - /de/
      - package.json
    translation: /%two_letters_code%/%two_letters_code%.json
  - source: '**.md'
    ignore:
      - /zh*
      - /de/
    translation: /%two_letters_code%/%original_path%/%original_file_name%
